# Copy-pasted from circleci.com

# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      PROJECT_NAME: brawl-haus
      PROJECT_ID: dev
      REGISTRY: eu.gcr.io
      #CLUSTER_NAME: docker-hello-google-cluster
      #CLOUDSDK_COMPUTE_ZONE: us-central1-f
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    
    pre:
      #- docker tag us.gcr.io/${PROJECT_NAME}/hello:$CIRCLE_SHA1 us.gcr.io/${PROJECT_NAME}/hello:latest
    #- sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update --version 120.0.0
    #- sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update --version 120.0.0 kubectl
    #- echo $ACCT_AUTH | base64 --decode > ${HOME}//gcloud-service-key.json
    #- sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    #- sudo /opt/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
    #- sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $CLUSTER_NAME
    #- sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
    #- sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $CLUSTER_NAME

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - setup_remote_docker

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
        
      # run tests!
      #- run: lein test

      # build and push 
      - run: |
          docker build -t ${REGISTRY}/${PROJECT_NAME}/${PROJECT_ID}:latest .
          docker login -u "_json_key" -p "$GCI_JSON_TOKEN" https://eu.gcr.io
          docker push ${REGISTRY}/${PROJECT_NAME}/${PROJECT_ID}:latest

      # deploy image
      #- run: sudo /opt/google-cloud-sdk/bin/gcloud docker -- push us.gcr.io/${PROJECT_NAME}/hello

      # publish
      #- run: sudo docker push andrewzhurov/brawl-haus-master:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
